# Generated by Django 4.0 on 2025-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_file',
            field=models.FileField(blank=True, null=True, upload_to='work_files/'),
        ),
    ]
