# Generated by Django 4.0 on 2025-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_password_employee_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
