# Generated by Django 4.0 on 2025-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notification_seen',
            field=models.BooleanField(default=True),
        ),
    ]
