# Generated by Django 4.0 on 2025-01-21 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
